on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: corepack enable pnpm
    - run: pnpm install
    - run: pnpm lint
    - run: xvfb-run -a pnpm test
    - run: pnpm package
