on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: corepack enable pnpm
    - name: Install
      run: pnpm install
    - name: Lint
      run: pnpm lint
    - name: Test
      run: xvfb-run -a pnpm test
    - name: Package
      run: pnpm package
    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: pnpm run publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
